name: build-android-Tv

# æ¨é€Tagæ—¶è§¦å‘ æˆ–è€… æ‰‹åŠ¨è§¦å‘
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: false
        default: 'v1.0.0'
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - name: ç­¾å‡ºä»£ç 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      # APKç­¾åè®¾ç½®
      - name: ä¸‹è½½Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: åˆ›å»ºkey.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      # è®¾ç½®JAVAç¯å¢ƒ
      - name: è®¾ç½®JAVAç¯å¢ƒ
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      # è®¾ç½®Flutter
      - name: è®¾ç½®Flutterç¯å¢ƒ
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # æ›´æ–°Flutterçš„packages
      - name: æ›´æ–°Flutterçš„packages
        run: flutter pub get

      # æ‰“åŒ…APK
      - name: æ‰“åŒ…APK
        run: flutter build apk --release --split-per-abi --android-skip-build-dependency-validation
      
      # ä¸Šä¼ APKè‡³Artifacts
      - name: ä¸Šä¼ APKè‡³Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: è¯»å–ç‰ˆæœ¬ä¿¡æ¯
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/version.json

      # ä¸Šä¼ è‡³Release
      # ä¸Šä¼ è‡³Release
      - name: ä¸Šä¼ è‡³Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          name: ${{ github.event.inputs.tag_name || github.ref_name }}
          body: |
            ğŸ“¦ çº¯ç²¹ç›´æ’­ ${{ github.ref_name }}
            æœ¬æ¬¡æ›´æ–°å†…å®¹ï¼š
            ${{ fromJson(steps.version.outputs.content).version_desc }}
            ğŸ”— ä¸‹è½½åœ°å€ï¼šhttps://github.com/liuchuancong/pure_live_TV/releases/latest
            æœ¬è½¯ä»¶ä¸ºå¼€æºé¡¹ç›®,æ— å¹¿å‘Šï¼Œæ— ç—…æ¯’ï¼Œè‹¥å®‰è£…æ—¶å‡ºç°ç—…æ¯’è¯¯æŠ¥ï¼Œå¯è‡ªè¡Œæ–Ÿé…Œã€‚
            ğŸ“º TV ç‰ˆæœ¬
            â€¢ å®‰è£…ç¨‹åºï¼šæ”¯æŒ Android TV 5.0+ (armeabi-v7a, arm64-v8a)
            â€¢ å·²å®ç°TVåŒæ­¥ç›´æ’­æº
            â€¢ æ”¯æŒå¤šç§æ’­æ”¾å™¨åˆ‡æ¢ 
            â€¢ æ”¯æŒå¼¹å¹•æ˜¾ç¤º
            â€¢ æ”¯æŒåº”ç”¨å…§æ›´æ–°
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # å®Œæˆ
      - name: è¾“å‡ºä»»åŠ¡çŠ¶æ€
        if: always()
        run: echo "ğŸ Android job's status is ${{ job.status }}."

  